"use strict";

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert("banks", [
      { name: "ABC CAPITAL" },
      { name: "AFIRME" },
      { name: "AMERICAN EXPRESS" },
      { name: "ANÁHUAC" },
      { name: "AUTOFIN" },
      { name: "AZTECA" },
      { name: "BAMSAS" },
      { name: "BANBAJÍO" },
      { name: "BANCEN" },
      { name: "BANCO DEL BIENESTAR" },
      { name: "BANCONFÍA" },
      { name: "BANCOPPEL" },
      { name: "BANCREA" },
      { name: "BANCRECER" },
      { name: "BANK NEW YORK" },
      { name: "BANK OF CHINA" },
      { name: "BANK ONE" },
      { name: "BANKAOOL" },
      { name: "BANORTE" },
      { name: "BANPAÍS" },
      { name: "BANREGIO" },
      { name: "BANSI" },
      { name: "BARCLAYS" },
      { name: "BBVA BANCOMER" },
      { name: "BICENTENARIO" },
      { name: "BM BASE" },
      { name: "BNP" },
      { name: "BOSTON" },
      { name: "CAPITAL" },
      { name: "CIBANCO" },
      { name: "CITIBANAMEX" },
      { name: "CITIBANK" },
      { name: "COMPARTAMOS BANCO" },
      { name: "CONSUBANCO" },
      { name: "CREMI" },
      { name: "DEL ATLANTICO" },
      { name: "DEL SURESTE" },
      { name: "DEUTSCHE" },
      { name: "DONDÉ" },
      { name: "FINTERRA" },
      { name: "FORJADORES" },
      { name: "FUJI" },
      { name: "GE MONEY" },
      { name: "HSBC" },
      { name: "INBURSA" },
      { name: "INDUSTRIAL" },
      { name: "ING" },
      { name: "INMOBILIARIO" },
      { name: "INTERACCIONES" },
      { name: "INTERBANCO" },
      { name: "INVESTA BANK" },
      { name: "INVEX" },
      { name: "IXE" },
      { name: "JP MORGAN" },
      { name: "MIFEL" },
      { name: "MONEX" },
      { name: "NATIONSBANK" },
      { name: "OBRERO" },
      { name: "ORIENTE" },
      { name: "PAGATODO" },
      { name: "PROGRESO" },
      { name: "PROMEX" },
      { name: "PUADRUM" },
      { name: "REPUBLIC NY" },
      { name: "SANTANDER" },
      { name: "SCOTIABANK" },
      { name: "SERFIN" },
      { name: "SOCIÉTÉ" },
      { name: "STP" },
      { name: "TOKYO" },
      { name: "UNIÓN" },
      { name: "VE POR MÁS" },
      { name: "VOLKSWAGEN BANK" },
    ]);
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete("banks", null, {});
  },
};
